# action.yml
name: 'SSH Deploy Github Action'
description: 'Deploy production ready code via SSH'
inputs:
  host:
    description: 'SSH server host'
    required: true
  port:
    description: 'SSH server port'
    required: false
    default: '22'
  username:
    description: 'SSH user'
    required: true
  key:
    description: 'SSH key'
  repository:
    description: 'Repository name'
outputs:
  list:
    description: 'List directory'
  whereami:
    description: 'Get current directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.key }}
    - ${{ inputs.repository }}
