# action.yml
name: 'SSH Deploy Github Action'
description: 'Deploy production ready code via SSH'
inputs:
  host:
    description: 'Who to greet'
    required: true
  port:
    description: 'Who to greet'
    required: false
    default: '22'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
