#!/bin/sh -l

echo "INPUT_HOST: $INPUT_HOST"
echo "INPUT_PORT: $INPUT_PORT"
echo "INPUT_USERNAME: $INPUT_USERNAME"
echo "HOME: $HOME"
echo "GITHUB_JOB: $GITHUB_JOB"
echo "INPUT_HOST: $INPUT_HOST"
echo "GITHUB_REF: $GITHUB_REF"
echo "GITHUB_SHA: $GITHUB_SHA"
echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"


ls -lah


pwd
